---
name: Ingress proxy
version: 0.2.4
slug: ingress_proxy
description: nginx reverse proxy to expose network resources through HA ingress
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
init: false
ingress: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl
options:
  dest_sabnzb_url: "http://192.168.0.1"
  dest_sabnzb_part: "sabnzbd"
  dest_radarr_url: "http://192.168.0.1"
  dest_radarr_part: "radarr"
  dest_sonarr_url: "http://192.168.0.1"
  dest_sonarr_part: "sonarr"
schema:
  dest_sabnzb_url: str?
  dest_sabnzb_part: str?
  dest_radarr_url: str?
  dest_radarr_part: str?
  dest_sonarr_url: str?
  dest_sonarr_part: str?